// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4kOUbEECLHcegGEFFcyz1DI29iCvITaU',
    appId: '1:922736238776:web:86bef73fc589b7607b544d',
    messagingSenderId: '922736238776',
    projectId: 'suenomotora-388ef',
    authDomain: 'suenomotora-388ef.firebaseapp.com',
    databaseURL: 'https://suenomotora-388ef-default-rtdb.firebaseio.com',
    storageBucket: 'suenomotora-388ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACAa5pn0gy52zSKzp4-_WlGU3OzRRfD1g',
    appId: '1:922736238776:android:9dcee2a251085c577b544d',
    messagingSenderId: '922736238776',
    projectId: 'suenomotora-388ef',
    databaseURL: 'https://suenomotora-388ef-default-rtdb.firebaseio.com',
    storageBucket: 'suenomotora-388ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNopSJfLAxNWmF_396m1fOey7z_EIzQsY',
    appId: '1:922736238776:ios:b72bc0689c0e0f527b544d',
    messagingSenderId: '922736238776',
    projectId: 'suenomotora-388ef',
    databaseURL: 'https://suenomotora-388ef-default-rtdb.firebaseio.com',
    storageBucket: 'suenomotora-388ef.appspot.com',
    iosClientId:
        '922736238776-bn76rsruc4h8f5thfo91slfp397n55i5.apps.googleusercontent.com',
    iosBundleId: 'com.example.suenomotoraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNopSJfLAxNWmF_396m1fOey7z_EIzQsY',
    appId: '1:922736238776:ios:8fa52c933b396bed7b544d',
    messagingSenderId: '922736238776',
    projectId: 'suenomotora-388ef',
    databaseURL: 'https://suenomotora-388ef-default-rtdb.firebaseio.com',
    storageBucket: 'suenomotora-388ef.appspot.com',
    iosClientId:
        '922736238776-e000htsnp4bsg359go2h3i2jhbv2lsiu.apps.googleusercontent.com',
    iosBundleId: 'com.lasuenomotora.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
      apiKey: "AIzaSyA4kOUbEECLHcegGEFFcyz1DI29iCvITaU",
      authDomain: "suenomotora-388ef.firebaseapp.com",
      databaseURL: "https://suenomotora-388ef-default-rtdb.firebaseio.com",
      projectId: "suenomotora-388ef",
      storageBucket: "suenomotora-388ef.appspot.com",
      messagingSenderId: "922736238776",
      appId: "1:922736238776:web:71843370977072697b544d",
      measurementId: "G-ECV04FHZK1");
}
